export { AlbumRouter } from "./album/album.routes"
export { UserRouter } from "./user/user.routes"
export { PostRouter } from "./post/post.routes"
export { FriendsRouter } from "./friends/friends.routes"
export { ChatsRouter } from "./chats/chats.routes"